---
title: "Bachelor 2"
author: "Alberte Baggesgaard Seeberg"
date: "12/12/2018"
output: html_document
---

```{r setup, include=FALSE}
setwd("~/Desktop/5. Semester/Bachelor/Data/Bachelor")

library(stringr)
library(plyr)
library(dplyr)
library(tidyverse)
library(rethinking)
library(ggplot2)
library(lme4)
library(yarrr)
library(MuMIn)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
CIData=read.csv("CIData")
AllData=read.csv("AltData")
CIData=CIData[-1]
AllData=AllData[-1]

AllData$Condition=as.character(AllData$Condition)

AllData$Condition=gsub("CI_ex", "CI2", AllData$Condition)
AllData$Condition=gsub("CI_re", "CI1", AllData$Condition)
AllData$Condition=gsub("Control_y", "CON2", AllData$Condition)
AllData$Condition=gsub("Control_e", "CON1", AllData$Condition)

CIData$Condition=gsub("CI_ex", "CI2", CIData$Condition)
CIData$Condition=gsub("CI_re", "CI1", CIData$Condition)
# CIData=plyr::rename(CIData, c("Musikviden"="KnowledgeMusic"))

RECI <- subset(CIData, Condition=="CI1")
EXCI <- subset(CIData, Condition=="CI2")

PitchData <- subset(AllData, Deviant=="Pitch")
RhythmData <- subset(AllData, Deviant=="Rhythm")
TimbreData <- subset(AllData, Deviant=="Timbre")
IntensityData <- subset(AllData, Deviant=="Intensitet")
PitchCI <- subset(CIData, Deviant=="Pitch")
RhythmCI <- subset(CIData, Deviant=="Rhythm")
TimbreCI <- subset(CIData, Deviant=="Timbre")
IntensityCI <- subset(CIData, Deviant=="Intensitet")


CIData$KnowledgeMusic=ordered(CIData$KnowledgeMusic, levels = c("1", "2", "3", "4","5"))

CIData$Lyttevaner=ordered(CIData$Lyttevaner, levels = c("0-2 timer", "3-5 timer", "6-8 timer", "9 eller flere"))

#Sammenlign Kontroller med CI brugere i forskellige 

m1=glmer(Correct~Group+(1|ID), data=AllData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
summary(m1)

r.squaredGLMM(m1)

#Intensity
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = IntensityData, main = "Intensity Results", xlab = "Intensity Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 


#Pitch
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = PitchData, main = "Pitch Results", xlab = "Pitch Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 

#Timbre
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = TimbreData, main = "Timbre Results", xlab = "Timbre Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 

#Rhythm
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = RhythmData, main = "Rhythm Results", xlab = "Rhythm Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 


#Modeller for CIData

m2=glmer(Correct~Condition*AlderOP+(1|ID), data=CIData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
summary(m2)

pirateplot(formula = Correct ~ Condition + DeviantLevel, data = CIData, main = "Results", xlab = "group",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 

m3=glmer(Correct~Condition*AlderOP+AarUdenHoerelse+(1|ID), data=CIData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
summary(m3)


m4=glmer(Correct~Condition*AlderOP+AarUdenHoerelse+KnowledgeMusic+(1|ID), data=CIData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
summary(m4)


M5=glmer(Correct~Condition*AlderOP+AarUdenHoerelse+KnowledgeMusic+DeviantLevel+(1|ID), data=CIData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
summary(M5)

M6=glmer(Correct~Condition*AlderOP+AarUdenHoerelse+KnowledgeMusic+Condition*Deviant*DeviantLevel+Lyttevaner+(1|ID), data=CIData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))
summary(M6)
vcov(M6)

anova(m2,m3,m4,M5, M6)

Nullmodel=glmer(Correct~1+(1|ID), data=CIData, family=binomial, control = glmerControl(optimizer = "nloptwrap", calc.derivs = FALSE))

#sammenligning af bedste model med nulmodel
anova(Nullmodel,M6)

r.squaredGLMM(M6)
#R2m=0.445869 , R2c=0.4530933


#Plot for KnowledgeMusic
pirateplot(formula = Correct ~ KnowledgeMusic + DeviantLevel, data = CIData, main = "Knowledge of Music and Performance", xlab = "group",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="ipod", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.33, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed")

#Plot for alder for operationen og lyttevaner
ggplot(CIData, aes(AlderOP, Correct, color=Condition))+geom_smooth(method=lm)+labs(x="AgeSurgery", y="PercentageCorrect", title="Age when Implanted and Performance")

ggplot(CIData, aes(as.numeric(Lyttevaner), Correct, color=Condition))+geom_smooth(method=lm)+labs(x="ListeningHabits", y="PercentageCorrect", title="Listening Habits and Performance")

ggplot(CIData, aes(as.numeric(KnowledgeMusic), Correct, color=Condition))+geom_smooth(method=lm)+labs(x="Knowledge og Music", y="PercentageCorrect", title="Knowledge of Music and Performance")

ggplot(RECI, aes(as.numeric(AarUdenHoerelse), Correct, color=Condition))+geom_smooth(method=lm)+labs(x="Years of Deafness", y="PercentageCorrect", title="Years of Deafness and Performance")

ggplot(EXCI, aes(as.numeric(AarUdenHoerelse), Correct, color=Condition))+geom_smooth(method=lm)+labs(x="Years of Deafness", y="PercentageCorrect", title="Years of Deafness and Performance")

pirateplot(formula = Correct ~ Lyttevaner + DeviantLevel, data = CIData, main = "Knowledge of Music and Performance", xlab = "group",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="ipod", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.33, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed")


#Plots for CI-brugere på tværs af devianter
#Intensity
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = IntensityCI, main = "Intensity Results", xlab = "Intensity Deviant",ylab="Correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 


#Pitch
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = PitchCI, main = "Pitch Results", xlab = "Pitch Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 

#Timbre
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = TimbreCI, main = "Timbre Results", xlab = "Timbre Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 

#Rhythm
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = RhythmCI, main = "Rhythm Results", xlab = "Rhythm Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="info", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3333, b=0, lwd=2, lty="dashed") 
```

