---
title: "Bachelor"
author: "Alberte Baggesgaard Seeberg"
date: "20/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Desktop/5. Semester/Bachelor/Data/Bachelor")

library(stringr)
library(plyr)
library(dplyr)
library(tidyverse)
library(rethinking)
library(ggplot2)

#All data cleaning

# filelistno=list.files(path="~/Desktop/5. Semester/Bachelor/Data/Bachelor/NO", pattern="*.csv", full.names=TRUE)
# NO=NULL
# 
# for (f in filelistno) {
#   t = read_csv2(f, stringsAsFactors=TRUE)
#   
#   if (exists("NO")){NO=rbind(NO,t)} else { NO=t }
# 
# 
# }

#Importer nyopererede
NO <- do.call("rbind", lapply( list.files("~/Desktop/5. Semester/Bachelor/Data/Bachelor/NO",full=TRUE),
		read.csv2, header=TRUE))

NO$Correct=as.integer(NO$Correct)
NO$Correct=gsub("[4]", "0", NO$Correct)
NO$Correct=gsub("[3]", "0", NO$Correct)
NO$Correct=gsub("[2]", "0", NO$Correct)
  
NO=plyr::rename(NO, c("No."="No"))

# NO$No=gsub("\\..*","",NO$No)
# 
# dataid1 <- NO[ which(NO$ID=='1'), ]
# 
# NO$No=gsub(" ","",NO$No)

NO$Condition="NoCI"

# Replaces <- data.frame(from = c("1"), to = c("IntensitetXS"))
# 
#                        
# FindReplace(data=NO, Var="No", replaceData=Replaces, from = "from", to = "to", vector=TRUE)
# 


#Making Deviants--------

NO$Deviant[NO$No == "1"] = "IntensitetXS"  
NO$Deviant[NO$No == "17"] = "IntensitetXS"  
NO$Deviant[NO$No == "33"] = "IntensitetXS"  
NO$Deviant[NO$No == "2"] = "IntensitetS" 
NO$Deviant[NO$No == "18"] = "IntensitetS"  
NO$Deviant[NO$No == "34"] = "IntensitetS"
NO$Deviant[NO$No == "3"] = "IntensitetL"  
NO$Deviant[NO$No == "19"] = "IntensitetL"  
NO$Deviant[NO$No == "35"] = "IntensitetL"  
NO$Deviant[NO$No == "4"] = "IntensitetXL"  
NO$Deviant[NO$No == "20"] = "IntensitetXL"  
NO$Deviant[NO$No == "36"] = "IntensitetXL"
NO$Deviant[NO$No == "5"] = "PitchXS" 
NO$Deviant[NO$No == "21"] = "PitchXS" 
NO$Deviant[NO$No == "37"] = "PitchXS" 
NO$Deviant[NO$No == "6"] = "PitchS" 
NO$Deviant[NO$No == "22"] = "PitchS" 
NO$Deviant[NO$No == "38"] = "PitchS" 
NO$Deviant[NO$No == "7"] = "PitchL" 
NO$Deviant[NO$No == "23"] = "PitchL" 
NO$Deviant[NO$No == "39"] = "PitchL" 
NO$Deviant[NO$No == "8"] = "PitchXL"
NO$Deviant[NO$No == "24"] = "PitchXL"
NO$Deviant[NO$No == "40"] = "PitchXL"
NO$Deviant[NO$No == "9"] = "TimbreBright"
NO$Deviant[NO$No == "25"] = "TimbreBright"
NO$Deviant[NO$No == "41"] = "TimbreBright"
NO$Deviant[NO$No == "10"] = "TimbreBlues"
NO$Deviant[NO$No == "26"] = "TimbreBlues"
NO$Deviant[NO$No == "42"] = "TimbreBlues"
NO$Deviant[NO$No == "11"] = "TimbreGuitar"
NO$Deviant[NO$No == "27"] = "TimbreGuitar"
NO$Deviant[NO$No == "43"] = "TimbreGuitar"
NO$Deviant[NO$No == "12"] = "TimbreTrumpet"
NO$Deviant[NO$No == "28"] = "TimbreTrumpet"
NO$Deviant[NO$No == "44"] = "TimbreTrumpet"
NO$Deviant[NO$No == "13"] = "RhythmXS"
NO$Deviant[NO$No == "29"] = "RhythmXS"
NO$Deviant[NO$No == "45"] = "RhythmXS"
NO$Deviant[NO$No == "14"] = "RhythmS"
NO$Deviant[NO$No == "30"] = "RhythmS"
NO$Deviant[NO$No == "46"] = "RhythmS"
NO$Deviant[NO$No == "15"] = "RhythmL"
NO$Deviant[NO$No == "31"] = "RhythmL"
NO$Deviant[NO$No == "47"] = "RhythmL"
NO$Deviant[NO$No == "16"] = "RhythmXL"
NO$Deviant[NO$No == "32"] = "RhythmXL"
NO$Deviant[NO$No == "48"] = "RhythmXL"

#------


NO$DeviantLevel = rep(NA,nrow(NO))

for (i in 1:nrow(NO)) {

  if (str_detect(NO$Deviant[i], "XS")){
    NO$DeviantLevel[i] = 1
  }
  NO$Deviant[i]=sub("XS","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "S")){
    NO$DeviantLevel[i] = 2
  }
  NO$Deviant[i]=sub("S","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "XL")){
    NO$DeviantLevel[i] = 4
  }
  NO$Deviant[i]=sub("XL","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "L")){
    NO$DeviantLevel[i] = 3
  }
  NO$Deviant[i]=sub("L","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "Bright")){
    NO$DeviantLevel[i] = 1
  }
  NO$Deviant[i]=sub("Bright","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "Blues")){
    NO$DeviantLevel[i] = 2
  }
  NO$Deviant[i]=sub("Blues","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "Guitar")){
    NO$DeviantLevel[i] = 3
  }
  NO$Deviant[i]=sub("Guitar","",NO$Deviant[i])
  
  if (str_detect(NO$Deviant[i], "Trumpet")){
    NO$DeviantLevel[i] = 4
  }
  NO$Deviant[i]=sub("Trumpet","",NO$Deviant[i])
  
}



write.csv(NO, file="NOdata")


#Importer Erfarne
ER <- do.call("rbind", lapply( list.files("~/Desktop/5. Semester/Bachelor/Data/Bachelor/Erfarne",full=TRUE),
		read.csv2, header=TRUE))


ER$Correct=as.integer(ER$Correct)
ER$Correct=gsub("[4]", "0", ER$Correct)
ER$Correct=gsub("[3]", "0", ER$Correct)
ER$Correct=gsub("[2]", "0", ER$Correct)
  
ER$Condition="ErCI"


#Making Deviants--------

ER$Deviant[ER$No == "1"] = "IntensitetXS"  
ER$Deviant[ER$No == "17"] = "IntensitetXS"  
ER$Deviant[ER$No == "33"] = "IntensitetXS"  
ER$Deviant[ER$No == "2"] = "IntensitetS" 
ER$Deviant[ER$No == "18"] = "IntensitetS"  
ER$Deviant[ER$No == "34"] = "IntensitetS"
ER$Deviant[ER$No == "3"] = "IntensitetL"  
ER$Deviant[ER$No == "19"] = "IntensitetL"  
ER$Deviant[ER$No == "35"] = "IntensitetL"  
ER$Deviant[ER$No == "4"] = "IntensitetXL"  
ER$Deviant[ER$No == "20"] = "IntensitetXL"  
ER$Deviant[ER$No == "36"] = "IntensitetXL"
ER$Deviant[ER$No == "5"] = "PitchXS" 
ER$Deviant[ER$No == "21"] = "PitchXS" 
ER$Deviant[ER$No == "37"] = "PitchXS" 
ER$Deviant[ER$No == "6"] = "PitchS" 
ER$Deviant[ER$No == "22"] = "PitchS" 
ER$Deviant[ER$No == "38"] = "PitchS" 
ER$Deviant[ER$No == "7"] = "PitchL" 
ER$Deviant[ER$No == "23"] = "PitchL" 
ER$Deviant[ER$No == "39"] = "PitchL" 
ER$Deviant[ER$No == "8"] = "PitchXL"
ER$Deviant[ER$No == "24"] = "PitchXL"
ER$Deviant[ER$No == "40"] = "PitchXL"
ER$Deviant[ER$No == "9"] = "TimbreBright"
ER$Deviant[ER$No == "25"] = "TimbreBright"
ER$Deviant[ER$No == "41"] = "TimbreBright"
ER$Deviant[ER$No == "10"] = "TimbreBlues"
ER$Deviant[ER$No == "26"] = "TimbreBlues"
ER$Deviant[ER$No == "42"] = "TimbreBlues"
ER$Deviant[ER$No == "11"] = "TimbreGuitar"
ER$Deviant[ER$No == "27"] = "TimbreGuitar"
ER$Deviant[ER$No == "43"] = "TimbreGuitar"
ER$Deviant[ER$No == "12"] = "TimbreTrumpet"
ER$Deviant[ER$No == "28"] = "TimbreTrumpet"
ER$Deviant[ER$No == "44"] = "TimbreTrumpet"
ER$Deviant[ER$No == "13"] = "RhythmXS"
ER$Deviant[ER$No == "29"] = "RhythmXS"
ER$Deviant[ER$No == "45"] = "RhythmXS"
ER$Deviant[ER$No == "14"] = "RhythmS"
ER$Deviant[ER$No == "30"] = "RhythmS"
ER$Deviant[ER$No == "46"] = "RhythmS"
ER$Deviant[ER$No == "15"] = "RhythmL"
ER$Deviant[ER$No == "31"] = "RhythmL"
ER$Deviant[ER$No == "47"] = "RhythmL"
ER$Deviant[ER$No == "16"] = "RhythmXL"
ER$Deviant[ER$No == "32"] = "RhythmXL"
ER$Deviant[ER$No == "48"] = "RhythmXL"

#------


ER$DeviantLevel = rep(NA,nrow(ER))

for (i in 1:nrow(ER)) {

  if (str_detect(ER$Deviant[i], "XS")){
    ER$DeviantLevel[i] = 1
  }
  ER$Deviant[i]=sub("XS","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "S")){
    ER$DeviantLevel[i] = 2
  }
  ER$Deviant[i]=sub("S","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "XL")){
    ER$DeviantLevel[i] = 4
  }
  ER$Deviant[i]=sub("XL","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "L")){
    ER$DeviantLevel[i] = 3
  }
  ER$Deviant[i]=sub("L","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "Bright")){
    ER$DeviantLevel[i] = 1
  }
  ER$Deviant[i]=sub("Bright","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "Blues")){
    ER$DeviantLevel[i] = 2
  }
  ER$Deviant[i]=sub("Blues","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "Guitar")){
    ER$DeviantLevel[i] = 3
  }
  ER$Deviant[i]=sub("Guitar","",ER$Deviant[i])
  
  if (str_detect(ER$Deviant[i], "Trumpet")){
    ER$DeviantLevel[i] = 4
  }
  ER$Deviant[i]=sub("Trumpet","",ER$Deviant[i])
  
}

write.csv(ER, file="ERdata")

#Importer unge kontroller

UK <- do.call("rbind", lapply( list.files("~/Desktop/5. Semester/Bachelor/Data/Bachelor/KontrolUnge",full=TRUE),
		read.csv2, header=TRUE))


UK$Correct=as.integer(UK$Correct)
UK$Correct=gsub("[4]", "0", UK$Correct)
UK$Correct=gsub("[3]", "0", UK$Correct)
UK$Correct=gsub("[2]", "0", UK$Correct)

UK$Condition="UngK"

#Making Deviants--------

UK$Deviant[UK$No == "1"] = "IntensitetXS"  
UK$Deviant[UK$No == "17"] = "IntensitetXS"  
UK$Deviant[UK$No == "33"] = "IntensitetXS"  
UK$Deviant[UK$No == "2"] = "IntensitetS" 
UK$Deviant[UK$No == "18"] = "IntensitetS"  
UK$Deviant[UK$No == "34"] = "IntensitetS"
UK$Deviant[UK$No == "3"] = "IntensitetL"  
UK$Deviant[UK$No == "19"] = "IntensitetL"  
UK$Deviant[UK$No == "35"] = "IntensitetL"  
UK$Deviant[UK$No == "4"] = "IntensitetXL"  
UK$Deviant[UK$No == "20"] = "IntensitetXL"  
UK$Deviant[UK$No == "36"] = "IntensitetXL"
UK$Deviant[UK$No == "5"] = "PitchXS" 
UK$Deviant[UK$No == "21"] = "PitchXS" 
UK$Deviant[UK$No == "37"] = "PitchXS" 
UK$Deviant[UK$No == "6"] = "PitchS" 
UK$Deviant[UK$No == "22"] = "PitchS" 
UK$Deviant[UK$No == "38"] = "PitchS" 
UK$Deviant[UK$No == "7"] = "PitchL" 
UK$Deviant[UK$No == "23"] = "PitchL" 
UK$Deviant[UK$No == "39"] = "PitchL" 
UK$Deviant[UK$No == "8"] = "PitchXL"
UK$Deviant[UK$No == "24"] = "PitchXL"
UK$Deviant[UK$No == "40"] = "PitchXL"
UK$Deviant[UK$No == "9"] = "TimbreBright"
UK$Deviant[UK$No == "25"] = "TimbreBright"
UK$Deviant[UK$No == "41"] = "TimbreBright"
UK$Deviant[UK$No == "10"] = "TimbreBlues"
UK$Deviant[UK$No == "26"] = "TimbreBlues"
UK$Deviant[UK$No == "42"] = "TimbreBlues"
UK$Deviant[UK$No == "11"] = "TimbreGuitar"
UK$Deviant[UK$No == "27"] = "TimbreGuitar"
UK$Deviant[UK$No == "43"] = "TimbreGuitar"
UK$Deviant[UK$No == "12"] = "TimbreTrumpet"
UK$Deviant[UK$No == "28"] = "TimbreTrumpet"
UK$Deviant[UK$No == "44"] = "TimbreTrumpet"
UK$Deviant[UK$No == "13"] = "RhythmXS"
UK$Deviant[UK$No == "29"] = "RhythmXS"
UK$Deviant[UK$No == "45"] = "RhythmXS"
UK$Deviant[UK$No == "14"] = "RhythmS"
UK$Deviant[UK$No == "30"] = "RhythmS"
UK$Deviant[UK$No == "46"] = "RhythmS"
UK$Deviant[UK$No == "15"] = "RhythmL"
UK$Deviant[UK$No == "31"] = "RhythmL"
UK$Deviant[UK$No == "47"] = "RhythmL"
UK$Deviant[UK$No == "16"] = "RhythmXL"
UK$Deviant[UK$No == "32"] = "RhythmXL"
UK$Deviant[UK$No == "48"] = "RhythmXL"

#------

UK$DeviantLevel = rep(NA,nrow(UK))

for (i in 1:nrow(UK)) {

  if (str_detect(UK$Deviant[i], "XS")){
    UK$DeviantLevel[i] = 1
  }
  UK$Deviant[i]=sub("XS","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "S")){
    UK$DeviantLevel[i] = 2
  }
  UK$Deviant[i]=sub("S","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "XL")){
    UK$DeviantLevel[i] = 4
  }
  UK$Deviant[i]=sub("XL","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "L")){
    UK$DeviantLevel[i] = 3
  }
  UK$Deviant[i]=sub("L","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "Bright")){
    UK$DeviantLevel[i] = 1
  }
  UK$Deviant[i]=sub("Bright","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "Blues")){
    UK$DeviantLevel[i] = 2
  }
  UK$Deviant[i]=sub("Blues","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "Guitar")){
    UK$DeviantLevel[i] = 3
  }
  UK$Deviant[i]=sub("Guitar","",UK$Deviant[i])
  
  if (str_detect(UK$Deviant[i], "Trumpet")){
    UK$DeviantLevel[i] = 4
  }
  UK$Deviant[i]=sub("Trumpet","",UK$Deviant[i])
  
}

write.csv(UK, file="UKdata")

#Importer ældre kontroller

ÆK <- do.call("rbind", lapply( list.files("~/Desktop/5. Semester/Bachelor/Data/Bachelor/KontrolÆldre",full=TRUE),
		read.csv2, header=TRUE))


ÆK$Correct=as.integer(ÆK$Correct)
ÆK$Correct=gsub("[4]", "0", ÆK$Correct)
ÆK$Correct=gsub("[3]", "0", ÆK$Correct)
ÆK$Correct=gsub("[2]", "0", ÆK$Correct)
  
ÆK$Condition="ÆldK"

#Making Deviants--------

ÆK$Deviant[ÆK$No == "1"] = "IntensitetXS"  
ÆK$Deviant[ÆK$No == "17"] = "IntensitetXS"  
ÆK$Deviant[ÆK$No == "33"] = "IntensitetXS"  
ÆK$Deviant[ÆK$No == "2"] = "IntensitetS" 
ÆK$Deviant[ÆK$No == "18"] = "IntensitetS"  
ÆK$Deviant[ÆK$No == "34"] = "IntensitetS"
ÆK$Deviant[ÆK$No == "3"] = "IntensitetL"  
ÆK$Deviant[ÆK$No == "19"] = "IntensitetL"  
ÆK$Deviant[ÆK$No == "35"] = "IntensitetL"  
ÆK$Deviant[ÆK$No == "4"] = "IntensitetXL"  
ÆK$Deviant[ÆK$No == "20"] = "IntensitetXL"  
ÆK$Deviant[ÆK$No == "36"] = "IntensitetXL"
ÆK$Deviant[ÆK$No == "5"] = "PitchXS" 
ÆK$Deviant[ÆK$No == "21"] = "PitchXS" 
ÆK$Deviant[ÆK$No == "37"] = "PitchXS" 
ÆK$Deviant[ÆK$No == "6"] = "PitchS" 
ÆK$Deviant[ÆK$No == "22"] = "PitchS" 
ÆK$Deviant[ÆK$No == "38"] = "PitchS" 
ÆK$Deviant[ÆK$No == "7"] = "PitchL" 
ÆK$Deviant[ÆK$No == "23"] = "PitchL" 
ÆK$Deviant[ÆK$No == "39"] = "PitchL" 
ÆK$Deviant[ÆK$No == "8"] = "PitchXL"
ÆK$Deviant[ÆK$No == "24"] = "PitchXL"
ÆK$Deviant[ÆK$No == "40"] = "PitchXL"
ÆK$Deviant[ÆK$No == "9"] = "TimbreBright"
ÆK$Deviant[ÆK$No == "25"] = "TimbreBright"
ÆK$Deviant[ÆK$No == "41"] = "TimbreBright"
ÆK$Deviant[ÆK$No == "10"] = "TimbreBlues"
ÆK$Deviant[ÆK$No == "26"] = "TimbreBlues"
ÆK$Deviant[ÆK$No == "42"] = "TimbreBlues"
ÆK$Deviant[ÆK$No == "11"] = "TimbreGuitar"
ÆK$Deviant[ÆK$No == "27"] = "TimbreGuitar"
ÆK$Deviant[ÆK$No == "43"] = "TimbreGuitar"
ÆK$Deviant[ÆK$No == "12"] = "TimbreTrumpet"
ÆK$Deviant[ÆK$No == "28"] = "TimbreTrumpet"
ÆK$Deviant[ÆK$No == "44"] = "TimbreTrumpet"
ÆK$Deviant[ÆK$No == "13"] = "RhythmXS"
ÆK$Deviant[ÆK$No == "29"] = "RhythmXS"
ÆK$Deviant[ÆK$No == "45"] = "RhythmXS"
ÆK$Deviant[ÆK$No == "14"] = "RhythmS"
ÆK$Deviant[ÆK$No == "30"] = "RhythmS"
ÆK$Deviant[ÆK$No == "46"] = "RhythmS"
ÆK$Deviant[ÆK$No == "15"] = "RhythmL"
ÆK$Deviant[ÆK$No == "31"] = "RhythmL"
ÆK$Deviant[ÆK$No == "47"] = "RhythmL"
ÆK$Deviant[ÆK$No == "16"] = "RhythmXL"
ÆK$Deviant[ÆK$No == "32"] = "RhythmXL"
ÆK$Deviant[ÆK$No == "48"] = "RhythmXL"

#------

ÆK$DeviantLevel = rep(NA,nrow(ÆK))

for (i in 1:nrow(ÆK)) {

  if (str_detect(ÆK$Deviant[i], "XS")){
    ÆK$DeviantLevel[i] = 1
  }
  ÆK$Deviant[i]=sub("XS","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "S")){
    ÆK$DeviantLevel[i] = 2
  }
  ÆK$Deviant[i]=sub("S","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "XL")){
    ÆK$DeviantLevel[i] = 4
  }
  ÆK$Deviant[i]=sub("XL","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "L")){
    ÆK$DeviantLevel[i] = 3
  }
  ÆK$Deviant[i]=sub("L","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "Bright")){
    ÆK$DeviantLevel[i] = 1
  }
  ÆK$Deviant[i]=sub("Bright","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "Blues")){
    ÆK$DeviantLevel[i] = 2
  }
  ÆK$Deviant[i]=sub("Blues","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "Guitar")){
    ÆK$DeviantLevel[i] = 3
  }
  ÆK$Deviant[i]=sub("Guitar","",ÆK$Deviant[i])
  
  if (str_detect(ÆK$Deviant[i], "Trumpet")){
    ÆK$DeviantLevel[i] = 4
  }
  ÆK$Deviant[i]=sub("Trumpet","",ÆK$Deviant[i])
  
}


write.csv(ÆK, file="ÆKdata")

Q_NO=read.csv2("Spørgeskema_NO.csv", header=TRUE, sep=";")

#Renaming--------

Q_NO=plyr::rename(Q_NO, c("Dato.for.første.operation"="DatoOp1", "Dato.for.evt..anden.operation"="DatoOp2", "Hvor.gammel.var.du.da.de.høretab.opstod"="AlderHøretab", "Hvor.gammel.var.du.da.dit.høretab.blev.så.alvorligt.at.du.ikke.længere.havde.gavn.af.dit.høreapparat" = "AlderUdenGavnHøreapparat", "Kan.du.tale.i.telefon"="TaleTelefon", "Uddyb.1"="TaleTelefonUD.", "Havde.du.tinnitus.inden.din.CI.operation"="TinnitusPre", "Har.du.tinnitus.nu"="TinnitusPost", "Uddyb.2"="TinnitusUD.", "Bruger.du.høreapparat"="Høreapparat", "Uddyb.3"="HøreapparatUD.", "Sang...Instrument.Folkeskole"="SangInstrument1", "Sang...Instrument.Gymnasiet"="SangInstrument2", "Sang...Instrument.Videregående.uddannelse"="SangInstrument3", "Sang...Instrument.Efter.endt.uddannelse"="SangInstrument4", "Ikke.modtaget.sang..eller.instrumentundervisning"="SangInstrument0", "band...kor..eller.orkester.Folkeskole"="BandKorOrkester1","band...kor..eller.orkester.Gymnasiet"="BandKorOrkester2", "band...kor..eller.orkester.Videregående.uddannelse"="BandKorOrkester3", "band...kor..eller.orkester.Efter.endt.uddannelse"="BandKorOrkester4", "Ikke.modtaget.band...kor..eller.orkesterundervisning"="BandKorOrkester0", "Kurser.fag.i.musikhistorie.teori.Musikalske.aktiviteter.i.børnehaven"="MusikIBørnehave", "Kurser.fag.i.musikhistorie.teori.Musikundervisning.i.folkeskolen..år."="Musikundervisning1", "Kurser.fag.i.musikhistorie.teori.Gymnasie"="Musikundervisning2","Kurser.fag.i.musikhistorie.teori.Videregående.uddannelse"="Musikundervisning3", "Kurser.fag.i.musikhistorie.teori.Ved.siden.af.uddannelse"="MusikundervisningX", "Kurser.fag.i.musikhistorie.teori.Efter.uddannelse"="Musikundervisning4", "Kurser.fag.i.musikhistorie.teori.Ingen.undervisning"="Musikundervisning0", "Uddybende"= "MusikundervisningUD.", "Jeg.har.aldrig.modtaget.formel.musikundervisning.og.har.sjældent.lyttet.til.musik.tidligere..Jeg.har.kun.begrænset.viden.om.musik."="MusikViden1", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.jeg.lytter.til.musik..radio..TV..en.gang.imellem.koncerter..og.er.bekendt.med.populære.sange.og.musikere..Jeg.ved.ikke.noget.om.de.tekniske.aspekter.ved.musik.såsom.noder.og.akkorder..Jeg.kan.heller.ikke.spille.på.nogen.instrumenter."="MusikViden2", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.betragter.mig.selv.som..selvlært..musiker..Jeg.kan.spille.lidt.på.et.instrument..synge.og.eller.har.været.med.i.et.band.kor."="MusikViden3", "Jeg.har.modtaget.nogen.musikundervisning..såsom.instrument..sangundervisning..musikfag.i.skolen.eller.har.været.med.i.bands.og.eller.kor.i.folkeskolen.og.gymnasiet..Jeg.betragter.ikke.mig.selv.som.ekspert..men.jeg.kender.til.grundlæggende.musikalske.begreber."="MusikViden4", "Jeg.har.fået.en.del.musikundervisning.eller.været.med.i.bands.og.eller.kor.i.en.del.år..fx.i.folkeskolen..gymnasiet.og.lignende...Jeg.opfatter.mig.selv.som.velorienteret.med.hensyn.til.musik..Jeg.kan.læse.noder.akkorder.og.kender.en.del.til.musiktekniske.begreber."="MusikViden5", "Før..Jeg.betragtede.mig.selv.som.en.person..som.ofte.vælger.at.lytte.meget.til.musik..jeg.vælger.f.eks..at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.." ="SelvBetragtLyttevanerPre", "Uddyb.4"="SelvBetragtLyttevanerPreUD.", "Efter..Jeg.betragter.mig.selv.som.en.person..som.ofte.vælger.at.lytte.meget.til.musik..jeg.vælger.f.eks..at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.."="SelvBetragtLyttevanerPost", "Uddyb.5"="SelvBetragtLyttevanerPostUD.", "Før..Jeg.valgte.ofte.at.lytte.til.musik..f.eks..bevidst.at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.."="LyttervanerPre", "Efter..Jeg.vælger.at.lytte.til.musik..f.eks..bevidst.at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.."="LyttevanerPost"  ))

#------

Q_NO$DatoOp1[1]=Q_NO$DatoOp1[1]=""
Q_NO$DatoOp1[2]=Q_NO$DatoOp1[2]=""
Q_NO$DatoOp1[3]=Q_NO$DatoOp1[3]=""
Q_NO$DatoOp1[4]=Q_NO$DatoOp1[4]=""
Q_NO$DatoOp1[5]=Q_NO$DatoOp1[5]=""
Q_NO$DatoOp1[6]=Q_NO$DatoOp1[6]=""
Q_NO$DatoOp1[7]=Q_NO$DatoOp1[7]=""
Q_NO$DatoOp1[8]=Q_NO$DatoOp1[8]=""
Q_NO$DatoOp1[9]=Q_NO$DatoOp1[9]=""

  


Q_ER=read.csv2("Spørgeskema_EO.csv", header=TRUE, sep=";")
#names(Q_ER)
#Renaming------
Q_ER=plyr::rename(Q_ER, c("Dato.for.første.operation"="DatoOp1", "Dato.for.evt..anden.operation"="DatoOp2", "Hvor.gammel.var.du.da.de.høretab.opstod"="AlderHøretab", "Hvor.gammel.var.du.da.dit.høretab.blev.så.alvorligt.at.du.ikke.længere.havde.gavn.af.dit.høreapparat" = "AlderUdenGavnHøreapparat", "Kan.du.tale.i.telefon"="TaleTelefon", "Uddyb.1"="TaleTelefonUD.", "Havde.du.tinnitus.inden.din.CI.operation"="TinnitusPre", "Har.du.tinnitus.nu"="TinnitusPost", "Uddyb.2"="TinnitusUD.", "Bruger.du.høreapparat"="Høreapparat", "Uddyb.3"="HøreapparatUD.", "Sang...Instrument.Folkeskole"="SangInstrument1", "Sang...Instrument.Gymnasiet"="SangInstrument2", "Sang...Instrument.Videregående.uddannelse"="SangInstrument3", "Sang...Instrument.Efter.endt.uddannelse"="SangInstrument4", "Ikke.modtaget.sang..eller.instrumentundervisning"="SangInstrument0", "band...kor..eller.orkester.Folkeskole"="BandKorOrkester1","band...kor..eller.orkester.Gymnasiet"="BandKorOrkester2", "band...kor..eller.orkester.Videregående.uddannelse"="BandKorOrkester3", "band...kor..eller.orkester.Efter.endt.uddannelse"="BandKorOrkester4", "Ikke.modtaget.band...kor..eller.orkesterundervisning"="BandKorOrkester0", "Kurser.fag.i.musikhistorie.teori.Musikalske.aktiviteter.i.børnehaven"="MusikIBørnehave", "Kurser.fag.i.musikhistorie.teori.Musikundervisning.i.folkeskolen..år."="Musikundervisning1", "Kurser.fag.i.musikhistorie.teori.Gymnasie"="Musikundervisning2","Kurser.fag.i.musikhistorie.teori.Videregående.uddannelse"="Musikundervisning3", "Kurser.fag.i.musikhistorie.teori.Ved.siden.af.uddannelse"="MusikundervisningX", "Kurser.fag.i.musikhistorie.teori.Efter.uddannelse"="Musikundervisning4", "Kurser.fag.i.musikhistorie.teori.Ingen.undervisning"="Musikundervisning0", "Uddybende"= "MusikundervisningUD.", "Jeg.har.aldrig.modtaget.formel.musikundervisning.og.har.sjældent.lyttet.til.musik.tidligere..Jeg.har.kun.begrænset.viden.om.musik."="MusikViden1", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.jeg.lytter.til.musik..radio..TV..en.gang.imellem.koncerter..og.er.bekendt.med.populære.sange.og.musikere..Jeg.ved.ikke.noget.om.de.tekniske.aspekter.ved.musik.såsom.noder.og.akkorder..Jeg.kan.heller.ikke.spille.på.nogen.instrumenter."="MusikViden2", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.betragter.mig.selv.som..selvlært..musiker..Jeg.kan.spille.lidt.på.et.instrument..synge.og.eller.har.været.med.i.et.band.kor."="MusikViden3", "Jeg.har.modtaget.nogen.musikundervisning..såsom.instrument..sangundervisning..musikfag.i.skolen.eller.har.været.med.i.bands.og.eller.kor.i.folkeskolen.og.gymnasiet..Jeg.betragter.ikke.mig.selv.som.ekspert..men.jeg.kender.til.grundlæggende.musikalske.begreber."="MusikViden4", "Jeg.har.fået.en.del.musikundervisning.eller.været.med.i.bands.og.eller.kor.i.en.del.år..fx.i.folkeskolen..gymnasiet.og.lignende...Jeg.opfatter.mig.selv.som.velorienteret.med.hensyn.til.musik..Jeg.kan.læse.noder.akkorder.og.kender.en.del.til.musiktekniske.begreber."="MusikViden5", "Jeg.betragter.mig.selv.som.en.person..som.ofte.vælger.at.lytte.meget.til.musik..jeg.vælger.f.eks..at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.." ="SelvBetragtLyttevaner", "Uddyb.4"="SelvBetragtLyttevanerUD.",  "Jeg.vælger.at.lytte.til.musik..f.eks..bevidst.at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.."="Lyttevaner"  ))
#--------

Q_KU=read.csv2("Spørgeskema_KU.csv", header=TRUE, sep=";")
#names(Q_KU)
#Renaming------

Q_KU=plyr::rename(Q_KU, c("Sang...Instrument.Folkeskole"="SangInstrument1", "Sang...Instrument.Gymnasiet"="SangInstrument2", "Sang...Instrument.Videregående.uddannelse"="SangInstrument3", "Sang...Instrument.Efter.endt.uddannelse"="SangInstrument4", "Ikke.modtaget.sang..eller.instrumentundervisning"="SangInstrument0", "band...kor..eller.orkester.Folkeskole"="BandKorOrkester1","band...kor..eller.orkester.Gymnasiet"="BandKorOrkester2", "band...kor..eller.orkester.Videregående.uddannelse"="BandKorOrkester3", "band...kor..eller.orkester.Efter.endt.uddannelse"="BandKorOrkester4", "Ikke.modtaget.band...kor..eller.orkesterundervisning"="BandKorOrkester0", "Kurser.fag.i.musikhistorie.teori.Musikalske.aktiviteter.i.børnehaven"="MusikIBørnehave", "Kurser.fag.i.musikhistorie.teori.Musikundervisning.i.folkeskolen..år."="Musikundervisning1", "Kurser.fag.i.musikhistorie.teori.Gymnasie"="Musikundervisning2","Kurser.fag.i.musikhistorie.teori.Videregående.uddannelse"="Musikundervisning3", "Kurser.fag.i.musikhistorie.teori.Ved.siden.af.uddannelse..ja.eller.nej."="MusikundervisningX", "Kurser.fag.i.musikhistorie.teori..Efter.uddannelse"="Musikundervisning4", "Kurser.fag.i.musikhistorie.teori.Ingen.undervisning"="Musikundervisning0", "Uddybende"= "MusikundervisningUD.", "Jeg.har.aldrig.modtaget.formel.musikundervisning.og.har.sjældent.lyttet.til.musik.tidligere..Jeg.har.kun.begrænset.viden.om.musik."="MusikViden1", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.jeg.lytter.til.musik..radio..TV..en.gang.imellem.koncerter..og.er.bekendt.med.populære.sange.og.musikere..Jeg.ved.ikke.noget.om.de.tekniske.aspekter.ved.musik.såsom.noder.og.akkorder..Jeg.kan.heller.ikke.spille.på.nogen.instrumenter."="MusikViden2", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.betragter.mig.selv.som..selvlært..musiker..Jeg.kan.spille.lidt.på.et.instrument..synge.og.eller.har.været.med.i.et.band.kor."="MusikViden3", "Jeg.har.modtaget.nogen.musikundervisning..såsom.instrument..sangundervisning..musikfag.i.skolen.eller.har.været.med.i.bands.og.eller.kor.i.folkeskolen.og.gymnasiet..Jeg.betragter.ikke.mig.selv.som.ekspert..men.jeg.kender.til.grundlæggende.musikalske.begreber."="MusikViden4", "Jeg.har.fået.en.del.musikundervisning.eller.været.med.i.bands.og.eller.kor.i.en.del.år..fx.i.folkeskolen..gymnasiet.og.lignende...Jeg.opfatter.mig.selv.som.velorienteret.med.hensyn.til.musik..Jeg.kan.læse.noder.akkorder.og.kender.en.del.til.musiktekniske.begreber."="MusikViden5", "Jeg.betragter.mig.selv.som.en.person..som.ofte.vælger.at.lytte.meget.til.musik..jeg.vælger.f.eks..at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.." ="SelvBetragtLyttevaner", "Uddyb"="SelvBetragtLyttevanerUD.",  "Jeg.vælger.at.lytte.til.musik..f.eks..bevidst.at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.."="Lyttevaner"  ))
#------

Q_KÆ=read.csv2("Spørgeskema_KÆ.csv", header=TRUE, sep=";")
#Renaming------

Q_KÆ=plyr::rename(Q_KÆ, c("Sang...Instrument.Folkeskole"="SangInstrument1", "Sang...Instrument.Gymnasiet"="SangInstrument2", "Sang...Instrument.Videregående.uddannelse"="SangInstrument3", "Sang...Instrument.Efter.endt.uddannelse"="SangInstrument4", "Ikke.modtaget.sang..eller.instrumentundervisning"="SangInstrument0", "band...kor..eller.orkester.Folkeskole"="BandKorOrkester1","band...kor..eller.orkester.Gymnasiet"="BandKorOrkester2", "band...kor..eller.orkester.Videregående.uddannelse"="BandKorOrkester3", "band...kor..eller.orkester.Efter.endt.uddannelse"="BandKorOrkester4", "Ikke.modtaget.band...kor..eller.orkesterundervisning"="BandKorOrkester0", "Kurser.fag.i.musikhistorie.teori.Musikalske.aktiviteter.i.børnehaven"="MusikIBørnehave", "Kurser.fag.i.musikhistorie.teori.Musikundervisning.i.folkeskolen..år."="Musikundervisning1", "Kurser.fag.i.musikhistorie.teori.Gymnasie"="Musikundervisning2","Kurser.fag.i.musikhistorie.teori.Videregående.uddannelse"="Musikundervisning3", "Kurser.fag.i.musikhistorie.teori.Ved.siden.af.uddannelse"="MusikundervisningX", "Kurser.fag.i.musikhistorie.teori.Efter.uddannelse"="Musikundervisning4", "Kurser.fag.i.musikhistorie.teori.Ingen.undervisning"="Musikundervisning0", "Uddybende"= "MusikundervisningUD.", "Jeg.har.aldrig.modtaget.formel.musikundervisning.og.har.sjældent.lyttet.til.musik.tidligere..Jeg.har.kun.begrænset.viden.om.musik."="MusikViden1", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.jeg.lytter.til.musik..radio..TV..en.gang.imellem.koncerter..og.er.bekendt.med.populære.sange.og.musikere..Jeg.ved.ikke.noget.om.de.tekniske.aspekter.ved.musik.såsom.noder.og.akkorder..Jeg.kan.heller.ikke.spille.på.nogen.instrumenter."="MusikViden2", "Jeg.har.aldrig.modtaget.formel.musikundervisning..men.betragter.mig.selv.som..selvlært..musiker..Jeg.kan.spille.lidt.på.et.instrument..synge.og.eller.har.været.med.i.et.band.kor."="MusikViden3", "Jeg.har.modtaget.nogen.musikundervisning..såsom.instrument..sangundervisning..musikfag.i.skolen.eller.har.været.med.i.bands.og.eller.kor.i.folkeskolen.og.gymnasiet..Jeg.betragter.ikke.mig.selv.som.ekspert..men.jeg.kender.til.grundlæggende.musikalske.begreber."="MusikViden4", "Jeg.har.fået.en.del.musikundervisning.eller.været.med.i.bands.og.eller.kor.i.en.del.år..fx.i.folkeskolen..gymnasiet.og.lignende...Jeg.opfatter.mig.selv.som.velorienteret.med.hensyn.til.musik..Jeg.kan.læse.noder.akkorder.og.kender.en.del.til.musiktekniske.begreber."="MusikViden5", "Jeg.betragter.mig.selv.som.en.person..som.ofte.vælger.at.lytte.meget.til.musik..jeg.vælger.f.eks..at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.." ="SelvBetragtLyttevaner", "Uddyb"="SelvBetragtLyttevanerUD.",  "Jeg.vælger.at.lytte.til.musik..f.eks..bevidst.at.høre.radio.i.bilen.eller.hjemme..gå.til.koncerter..se.musikprogrammer.i.fjernsynet..osv.."="Lyttevaner"  ))
#------




NO_all=merge(NO,Q_NO,by="ID")

AllCond=dplyr::bind_rows(NO, ER, UK, ÆK)

```



```{r}
#Analysis

library(lme4)
library(yarrr)

AllCond$Correct=as.integer(AllCond$Correct)
AllCond$Condition=as.factor(AllCond$Condition)

PitchData <- subset(AllCond, Deviant=="Pitch")
RhythmData <- subset(AllCond, Deviant=="Rhythm")
TimbreData <- subset(AllCond, Deviant=="Timbre")
IntensityData <- subset(AllCond, Deviant=="Intensitet")


#Intensity
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = IntensityData, main = "Intensity Results", xlab = "Intensity Deviant",ylab="Correct", ylim= c(0,1), theme=2, pal="ipod", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3,0.3, b=0, lwd=2, lty="dashed") 




#Pitch
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = PitchData, main = "Pitch Results", xlab = "Intensity Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="ipod", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3,0.3, b=0, lwd=2, lty="dashed") 

#Timbre
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = TimbreData, main = "Pitch Results", xlab = "Intensity Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="ipod", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3,0.3, b=0, lwd=2, lty="dashed") 

#Rhythm
pirateplot(formula = Correct ~ Condition + DeviantLevel, data = RhythmData, main = "Pitch Results", xlab = "Intensity Deviant",ylab="Percentage correct", ylim= c(0,1), theme=2, pal="ipod", avg.line.o=0.8, bar.f.o = .2, bean.b.o = .7, point.o = 0.3, point.pch = 1, back.col = "white") +
  abline(a=0.3,0.3, b=0, lwd=2, lty="dashed") 

model1 = glmer(Correct ~ Condition+(1|ID), data=AllCond, family=poisson)
summary(model1)


model2 = glmer(Correct ~Condition*Deviant*DeviantLevel+(1|ID), data=AllCond, family=poisson)
summary(model2)
print(model2, correlation=TRUE)
```


```{r}

```
